# Basic
title: 叶本晨
subtitle: BenchenYe
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: 领域
# 头像里面的描述
avatarDesc: R / Python
url: "https://github.com/bencheye/bencheye.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    #disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    github: bencheye
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: benche1993@163.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
    #id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
   # id: UA-84134159-3  
    #host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: Resume, description: support, url: '/resume'}      
    - {title: 中文简历, description: about, url: '/chineseCV'}   
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

#简历打印样式设置
subject-width: 20% #左边栏宽度
print:
  # 打印样式模板,
  # 空不设置打印样式，模板变量无效
  # basic:网页基本一致，
  # flex: 侧栏密集排版，
  # block:无侧栏
  template: 'basic' 
  #字体大小
  fontsize: 12px
  #页面边距设置，3~5mm为佳[不建议修改]
  page-margin: '6mm 5mm 3mm' #上，右(无同上)，下(无同上)，左（无同右）
  #也顶部(姓名栏目)边距偏移
  header-padding: '8mm 0 3mm'
  #每块设置(对应main里面每一条)
  section:
    margin: '3px auto 0' #边距
    padding: '3px 0' #内部偏移
    width: '80%' #内容宽度 basic无效
  # content每一条边距设置
  block-margin: 4px 0
  #打印版页脚设置
  footer:
    top: 5px #上边距
    height: 50px #高度

exclude:
  - LICENSE
  - README.md
  - .gitignore

#额外js脚本
# scripts:
#   - src: "assets/js/ie.js"
#     defer: defer

timezone: '+0800'

# Compress html 压缩HTML
compress_html:
  #去除空格
  clippings: [html, head, title, base, link, meta, style, script, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, a, span, i, svg, summary, details, code,'!--[if lte IE 9]','![endif]--']
  #去除注释
  # comments: all

#css 合并压缩css
sass:
  style: compressed
  sass_dir: _sass


